name: Build and Test
description: Common build and test logic for Eidos

runs:
  using: "composite"
  steps:
    - name: 📦 Install dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y python3-colcon-common-extensions \
                            python3-pip \
                            build-essential \

    - name: 🧱 Build workspace
      shell: bash
      run: colcon build --merge-install

    - name: ✅ Run tests
      shell: bash
      run: |
        colcon test --merge-install --event-handlers console_cohesion+
        colcon test-result --verbose

    - name: 🗃️ Upload test logs as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: colcon-test-logs
        path: |
          build/**/Testing/**/*.log
